# =============================================================================
# FRAPPE CLOUD - FRAPPE/ERPNEXT SERVICES
# MariaDB + Redis + Frappe Backend + Workers
# =============================================================================
# PORT MAPPING (32000-32500 range):
#   MariaDB:           32306
#   Redis Cache:       32379
#   Redis Queue:       32380
# =============================================================================

services:
  # ---------------------------------------------------------------------------
  # MARIADB - Database Server
  # ---------------------------------------------------------------------------
  frappe-cloud-mariadb:
    image: docker.io/mariadb:10.11
    container_name: frappe-cloud-mariadb
    hostname: frappe-cloud-mariadb
    restart: unless-stopped
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-admin}
    ports:
      - "32306:3306"
    volumes:
      - frappe-cloud-mariadb-data:/var/lib/mysql
    networks:
      - frappe-cloud-internal
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # ---------------------------------------------------------------------------
  # REDIS CACHE
  # ---------------------------------------------------------------------------
  frappe-cloud-redis-cache:
    image: docker.io/redis:7-alpine
    container_name: frappe-cloud-redis-cache
    hostname: frappe-cloud-redis-cache
    restart: unless-stopped
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru
    ports:
      - "32379:6379"
    volumes:
      - frappe-cloud-redis-cache-data:/data
    networks:
      - frappe-cloud-internal
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ---------------------------------------------------------------------------
  # REDIS QUEUE
  # ---------------------------------------------------------------------------
  frappe-cloud-redis-queue:
    image: docker.io/redis:7-alpine
    container_name: frappe-cloud-redis-queue
    hostname: frappe-cloud-redis-queue
    restart: unless-stopped
    command: redis-server --appendonly yes
    ports:
      - "32380:6379"
    volumes:
      - frappe-cloud-redis-queue-data:/data
    networks:
      - frappe-cloud-internal
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ---------------------------------------------------------------------------
  # FRAPPE BACKEND (Gunicorn)
  # ---------------------------------------------------------------------------
  frappe-cloud-backend:
    image: docker.io/frappe/erpnext:v15
    container_name: frappe-cloud-backend
    hostname: frappe-cloud-backend
    restart: unless-stopped
    working_dir: /home/frappe/frappe-bench/sites
    command:
      - /home/frappe/frappe-bench/env/bin/gunicorn
      - --bind=0.0.0.0:8000
      - --workers=4
      - --timeout=120
      - --graceful-timeout=30
      - --chdir=/home/frappe/frappe-bench/sites
      - frappe.app:application
    volumes:
      - frappe-cloud-sites:/home/frappe/frappe-bench/sites
      - frappe-cloud-logs:/home/frappe/frappe-bench/logs
      - frappe-cloud-logs:/home/frappe/logs
    networks:
      - frappe-cloud-internal
    depends_on:
      frappe-cloud-configurator:
        condition: service_completed_successfully

  # ---------------------------------------------------------------------------
  # NGINX - Frontend Proxy & Static Assets Server
  # ---------------------------------------------------------------------------
  frappe-cloud-nginx:
    image: docker.io/frappe/erpnext:v15
    container_name: frappe-cloud-nginx
    hostname: frappe-cloud-nginx
    restart: unless-stopped
    entrypoint: []
    command:
      - nginx
      - -g
      - "daemon off;"
    volumes:
      - ../config/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro,z
      - frappe-cloud-sites:/home/frappe/frappe-bench/sites:ro
    networks:
      - frappe-cloud-proxy
      - frappe-cloud-internal
    depends_on:
      - frappe-cloud-backend
      - frappe-cloud-websocket

  # ---------------------------------------------------------------------------
  # FRAPPE WEBSOCKET (Socket.IO)
  # ---------------------------------------------------------------------------
  frappe-cloud-websocket:
    image: docker.io/frappe/erpnext:v15
    container_name: frappe-cloud-websocket
    hostname: frappe-cloud-websocket
    restart: unless-stopped
    working_dir: /home/frappe/frappe-bench
    command:
      - node
      - /home/frappe/frappe-bench/apps/frappe/socketio.js
    environment:
      SITES_PATH: /home/frappe/frappe-bench/sites
    volumes:
      - frappe-cloud-sites:/home/frappe/frappe-bench/sites:ro
      - frappe-cloud-logs:/home/frappe/frappe-bench/logs
    networks:
      - frappe-cloud-internal
    depends_on:
      frappe-cloud-configurator:
        condition: service_completed_successfully

  # ---------------------------------------------------------------------------
  # FRAPPE SCHEDULER
  # ---------------------------------------------------------------------------
  frappe-cloud-scheduler:
    image: docker.io/frappe/erpnext:v15
    container_name: frappe-cloud-scheduler
    hostname: frappe-cloud-scheduler
    restart: unless-stopped
    command: bench schedule
    volumes:
      - frappe-cloud-sites:/home/frappe/frappe-bench/sites
      - frappe-cloud-logs:/home/frappe/frappe-bench/logs
    networks:
      - frappe-cloud-internal
    depends_on:
      frappe-cloud-configurator:
        condition: service_completed_successfully

  # ---------------------------------------------------------------------------
  # FRAPPE WORKER - Short Queue
  # ---------------------------------------------------------------------------
  frappe-cloud-worker-short:
    image: docker.io/frappe/erpnext:v15
    container_name: frappe-cloud-worker-short
    hostname: frappe-cloud-worker-short
    restart: unless-stopped
    command: bench worker --queue short
    volumes:
      - frappe-cloud-sites:/home/frappe/frappe-bench/sites
      - frappe-cloud-logs:/home/frappe/frappe-bench/logs
    networks:
      - frappe-cloud-internal
    depends_on:
      frappe-cloud-configurator:
        condition: service_completed_successfully

  # ---------------------------------------------------------------------------
  # FRAPPE WORKER - Long Queue
  # ---------------------------------------------------------------------------
  frappe-cloud-worker-long:
    image: docker.io/frappe/erpnext:v15
    container_name: frappe-cloud-worker-long
    hostname: frappe-cloud-worker-long
    restart: unless-stopped
    command: bench worker --queue long
    volumes:
      - frappe-cloud-sites:/home/frappe/frappe-bench/sites
      - frappe-cloud-logs:/home/frappe/frappe-bench/logs
    networks:
      - frappe-cloud-internal
    depends_on:
      frappe-cloud-configurator:
        condition: service_completed_successfully

  # ---------------------------------------------------------------------------
  # CONFIGURATOR - One-time setup (init container pattern)
  # ---------------------------------------------------------------------------
  frappe-cloud-configurator:
    image: docker.io/frappe/erpnext:v15
    container_name: frappe-cloud-configurator
    hostname: frappe-cloud-configurator
    restart: "no"
    entrypoint: /bin/bash
    command:
      - -c
      - |
        set -e
        echo "â³ Waiting for MariaDB..."
        while ! mysqladmin ping -h frappe-cloud-mariadb -u root -p$${DB_ROOT_PASSWORD} --silent 2>/dev/null; do
          sleep 2
        done
        echo "âœ… MariaDB is ready!"
        
        echo "â³ Waiting for Redis (5 seconds)..."
        sleep 5
        echo "âœ… Redis should be ready!"
        
        # Initialize sites directory with proper files
        cd /home/frappe/frappe-bench
        
        if [ ! -f sites/apps.txt ]; then
          echo "ðŸ“ Initializing sites directory..."
          echo -e "frappe\nerpnext" > sites/apps.txt
        fi
        
        # Create/update common_site_config.json
        echo "âš™ï¸ Configuring common_site_config.json..."
        cat > sites/common_site_config.json << 'EOF'
        {
          "db_host": "frappe-cloud-mariadb",
          "db_port": 3306,
          "redis_cache": "redis://frappe-cloud-redis-cache:6379",
          "redis_queue": "redis://frappe-cloud-redis-queue:6379",
          "redis_socketio": "redis://frappe-cloud-redis-cache:6379",
          "socketio_port": 9000
        }
        EOF
        
        echo "âœ… Configuration complete!"
    environment:
      DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-admin}
    volumes:
      - frappe-cloud-sites:/home/frappe/frappe-bench/sites
      - frappe-cloud-logs:/home/frappe/frappe-bench/logs
    networks:
      - frappe-cloud-internal
    depends_on:
      frappe-cloud-mariadb:
        condition: service_healthy
      frappe-cloud-redis-cache:
        condition: service_healthy
      frappe-cloud-redis-queue:
        condition: service_healthy
